/run/initialize

/gps/source/add 1.
/gps/source/intensity 1
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0 -40 cm
/gps/pos/halfx 25 mm
/gps/pos/halfy 25 mm
/gps/direction 0 0 1
/gps/particle gamma
/gps/ene/type Arb
/gps/hist/file ./linac_gamma_hist.txt
/gps/hist/inter Lin

/gps/source/add 1.
/gps/source/intensity 0.115
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0 -40 cm
/gps/pos/halfx 25 mm
/gps/pos/halfy 25 mm
/gps/direction 0 0 1
/gps/particle e-
/gps/ene/type Arb
/gps/hist/file ./linac_e-_hist.txt
/gps/hist/inter Lin

/gps/source/add 1.
/gps/source/intensity 0.004
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0 -40 cm
/gps/pos/halfx 25 mm
/gps/pos/halfy 25 mm
/gps/direction 0 0 1
/gps/particle e+
/gps/ene/type Arb
/gps/hist/file ./linac_e+_hist.txt
/gps/hist/inter Lin

/gps/source/add 1.
/gps/source/intensity 0.012
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0 -40 cm
/gps/pos/halfx 25 mm
/gps/pos/halfy 25 mm
/gps/direction 0 0 1
/gps/particle neutron
/gps/ene/type Arb
/gps/hist/file ./linac_neutron_hist.txt
/gps/hist/inter Lin


/run/printProgress 1000
/run/beamOn 1000000
