# ======================================================= Geometry
/vis/geometry/set/colour Box 0 0.0 0.0 1.0 0.4

/vis/geometry/set/colour World 0 1.0 1.0 1.0 0.0
#/vis/geometry/set/forceWireframe World

# ======================================================= Objects

/vis/scene/add/magneticField
/vis/scene/add/electricField
#/vis/scene/add/axes 0 0 0 0.2

# ======================================================= Info
/vis/scene/add/date