/vis/open OGL 600x600-0+0

/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume

/vis/viewer/set/viewpointVector 0 0 0
/vis/viewer/set/lightsVector 1 1 1

/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

# ========================= CHANGED BLOCK HW2 =========================
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow

#/vis/modeling/trajectories/drawByParticleID-0/set gamma magenta
#/vis/modeling/trajectories/drawByParticleID-0/set proton red
#/vis/modeling/trajectories/drawByParticleID-0/set neutron gray
#/vis/modeling/trajectories/drawByParticleID-0/set alpha green

/vis/geometry/set/colour Box 255 0 255 1 1
/vis/geometry/set/colour Parallelepiped 0 255 0 1 1
# ========================= CHANGED BLOCK END =========================
/vis/scene/endOfEventAction accumulate


/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! exampleB1

/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)

/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.

/vis/geometry/set/visibility World 0 false

# "Envelope" is transparent blue to represent water
/vis/geometry/set/colour Envelope 0 0 0 1 .3
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
/vis/viewer/set/projection p


