# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: C++ Code Analysis

on:
  push:
    branches: [ main ]

jobs:
  analyze:
    permissions:
      contents: read
      security-events: write
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: C/C++ Lint Action
        uses: shenxianpeng/cpp-linter-action@v1.4.1
